### ISSUE TITLE
Absolute path not property handled

### ISSUE THREAD

**Issue by jairbubbles** [goelhardik/ignore#19]
```csharp
        [Fact]
        public void SimpleIgnore_Dotfiles_WithStar2() => GitBasedTest(
            @"""
.vs/*
""",
            new[] { "C:/foo/.vs/a.txt", "foo/.vs/a.txt", ".vs/a.txt" });
```

`C:/foo/.vs/a.txt` should be ignored by the lib and is not.

I'm not sure why "foo/.vs/a.txt" is not ignored though 😔

**Comment by jairbubbles** [comment]
Humm not sure the tests are supposed to handle properly the absolute paths.

**Comment by qubitz** [comment]
I was also attempting to use absolute paths and glad I came across this issue. Originally was thinking this was a bug, but relative paths make sense. Sidenote, perhaps absolute paths should be expressly prohibited?

For those curious, somewhere between 0.1.42 and 0.2.1, the resultant regex expressions for something like '.editorconfig' went from `^.editorconfig(/.*)?$` to `(^|/)\.editorconfig(/.*)?$`. Testing this regex showed no matches when an absolute path was specified.

Ultimately was fixed with
```cs
path = Path.GetRelativePath(rootDirectory, path);
ignore.IsIgnored(path);
```
